Add version subcommand
connorkuehl/popple pull request #15
Opened 2021-06-12 07:38 UTC by pradeepnnv

2021-06-13 18:51 UTC, connorkuehl requested changes
The command itself looks good but it is not currently reachable during normal operation.

You need to add an entry to the `cmds` array in `func doWork` in `job.go` so that during message parsing, Popple can recognize the `version` command and execute the code you wrote. Something like this:

```diff
diff --git a/job.go b/job.go
index fcbaddd..a80bd79 100644
--- a/job.go
+++ b/job.go
@@ -28,6 +28,7 @@ func doWork(job *Job, db *gorm.DB) {
                {"help", SendHelp, false},
                {"karma", CheckKarma, true},
                {"top", Top, false},
+               {"version", SendVersion, false},
        }

        msg := job.Message.ContentWithMentionsReplaced()
```

2021-06-13 18:51 UTC, connorkuehl commented on .gitignore
> +popple
Does the line above not ignore the executable?

2021-06-13 18:51 UTC, connorkuehl commented on version.go
> +const version = "1.1.0"
Please make it uppercase: `const Version = "1.1.0"`

2021-06-13 18:51 UTC, connorkuehl commented on popple.go
> +
I appreciate where you're going with this, but Popple isn't an interactive command line tool so I don't think we should add a switch like this. Please remove this.

2021-06-15 21:28 UTC, connorkuehl commented
Would you also be willing to document this command in the `README.md` with the other commands? Thanks.

2021-06-16 15:25 UTC, pradeepnnv commented
@connorkuehl , thanks for the feedback. i've made updates. Please review.

2021-06-16 22:31 UTC, connorkuehl commented
Merged as 4137d2f87f4b0b8da12671a2044388290dba8d9f.

Thanks!

2021-06-16 22:32 UTC, closed without merging